project:
  type: book

book:
  title: "Sampling design for monitoring boreal birds in Quebec"
  author:
    - name: Willian Vieira
      orcid: 0000-0003-0283-4570
    - name: Bruno Drolet
  search: true
  repo-url: "https://github.com/willvieira/sampling_BMS/"
  repo-actions: [issue]
  downloads: [pdf]
  sharing: [twitter]
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - studyArea.qmd
    - part: PSU inclusion probability
      chapters:
      - habitat.qmd
      - cost.qmd
      - legacy.qmd
    - part: Sampling design
      chapters:
      - PSU.qmd
      - SSU.qmd
    - part: Appendices
      chapters:
      - runGRTSexample.qmd
      - ecosumm_habitat.qmd
      - ecosumm_cost.qmd
      - ecosumm_legacySites.qmd
      - ecosumm_selection.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    keep-md: true
  pdf:
    documentclass: scrreprt
  docx:
    toc: false

number-depth: 1
